<a href="https://colab.research.google.com/github/eflatt/udemy-Complete-Tensorflow-2-and-Keras/blob/main/intro_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Arrays**




**To Import the numpy library:**



In [ ]:
import numpy as np

**Creating Arrays:**

Convert a python list into a numpy array:

In [ ]:
mylist = [1,2,3]
np.array(mylist)

Convert a nested python list into a numpy array (*note how numpy
will preserve the shape of the python nested list*):

In [ ]:
nested_list = [[1,2], [3,4], [5,6]]
np.array(nested_list)

**Generating Useful Arrays:**

Generate a numpy array from a range (by default of integers), note that it creates a semi-closed interval [a, b) and can optionally include a step size:

In [ ]:
np.arange(0,10)

In [ ]:
np.arange(0,10,2)

In [ ]:
np.arange(0,11,2)

Often in data science you want to create an array of just zeros or an array of just ones, as well as *I* the identity matrix:

In [ ]:
# note that the default is floating point precision
np.zeros(3)

In [ ]:
# if you pass it a shape (and/or type - defaults to floating point), you get that
np.zeros((3,3))

In [ ]:
# 3x3 matrix of just ones (defaults to floating pt type)
np.ones((3,3))

In [ ]:
# note that I is always square, so you only need specify one dimension
# also note that eye() defaults to floating pt rep
np.eye(3, dtype=int)

Usefully you can create evenly spaced points over a specified interval:

In [ ]:
# linspace(a,b,c) : Create c evenly spaced points across the *closed* interval [a,b]
np.linspace(0,10,3)

In [ ]:
# linspace (a,b,c) where c = 2*(b-a) + 1 so even spacing is 1/2
# note that this is a *closed* and not half-open interval
np.linspace(0,50,101)

You can create Random Arrays and Matrices:

In [ ]:
# For an array with 2 elements with values from the uniform distribution between [0,1]:
np.random.rand(2)

In [ ]:
# For a matrix with 3 rows and 4 columns with values from the uniform distribution between [0,1]:
np.random.rand(3,4)

In [ ]:
# For a matrix with 3 rows and 4 columns with values from the gaussian/normal distribution with
# mean at 0 and variance of 1
np.random.randn(3,4)

In [ ]:
# Pick a single random integeger between the semi closed interval of [a, b)
np.random.randint(1,100)

In [ ]:
# Return an array of c random integers between the semi closed interval of [a, b)
np.random.randint(1,100,10)

In [ ]:
# You can also create a random matrix with integer values on the semi closed interval of [a,b)
np.random.randint(1,101,(3,3))

In [ ]:
# If you want pseudo-randomness to make for reproduceable 'random' results, set the seed:
np.random.seed(42)
np.random.rand(4)

In [ ]:
# Note how the same seed gets you the same array of 4 random values:
np.random.seed(42)
np.random.rand(4)

**How to Reshape or figure out shape of a numpy matrix/array**

In [ ]:
# Create an array expressing an integer range from [0,25)
arr = np.arange(25)

In [ ]:
# Create an array of 10 integer elements whose values were chosen
# from the random distribution from the interval [0,50) 
ranarr = np.random.randint(0,50,10)

In [ ]:
# You can query the shape of the array (it's a property of the array
# arr.shape -> (25,) and ranarr.shape -> (50,)

In [ ]:
# You can reshape an existing array into a different matrix shape
# (so long as the dimensions come to the same)
arr.reshape((5,5))

In [ ]:
ranarr.reshape((5,2))

In [ ]:
# note however that reshape does NOT mutate the array:
# arr will yield the original 1x25 vector
arr

**How to find the max/min value (and where it lives) in an array:**

In [ ]:
ranarr

In [ ]:
# what is the max value in ranarr?
ranarr.max()

In [ ]:
# where is the max value in ranarr?
ranarr.argmax()

In [ ]:
# what is the min value in ranarr?
ranarr.min()

In [ ]:
# where is the min value in ranarr?
ranarr.argmin()

In [ ]:
foo.argmin()

**How to find out what *type* of values in an array/matrix are:**

In [ ]:
ranarr.dtype

*italicized text*# **Numpy Index Selection**




In [ ]:
#Create some arrays to demonstrate:
arr = np.arange(0,11)
arr

**Extract elements and ranges from an array:**

In [ ]:
# Extract the ith element from the list
arr[8]

In [ ]:
# Extract the ith-through *jth-1* elements from the list
arr[1:5]

In [ ]:
# Extracting from the beginning through ith element:
arr[:5]

In [ ]:
# Extracting from i through end of the array:
arr[5:]

**Broadcasting: means to assign a single value into a range of the original array**

In [ ]:
# Broadcast the value 100 across the first 5 elements of an array
# NOTE THAT THIS IS MUTABLE!!!!
arr[0:5] = 100
arr

In [ ]:
# Reset arr to be [0,10]
arr=np.arange(0,11)


**Note that by default, slices mutate (they are pointers) the array into which they point**

In [ ]:
# Get a MUTABLE ptr into arr
slice_of_arr = arr[0:5]

# Broadcast 99 to the entire slice_of_arr, note that this CHANGES arr
# Note foo[:] implies the entirety of the container
slice_of_arr[:] = 99

# arr will now have the 99 broadcast into it:
arr

**To NOT mutate the array into which a slice ptr points, you need to explicitly make a copy like this (Note that assignment or slicing by default gives you a mutable pointer into the original array):**

In [ ]:
# Reset arr to be [0,10]
arr=np.arange(0,11)

In [ ]:
# Make a copy of the original arr array
arr_copy = arr.copy()

# Slice into the copy:
arr_copy_slice = arr_copy[0:5]

# Mutate the copy:
arr_copy_slice[:] = 99
arr_copy


In [ ]:
# But the original array remains intact:
arr

**Indexing into a 2d array/matrix**

In [ ]:
# Create a 2d array by casting a python list of lists into a numpy array:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [ ]:
# How many Rows and Columns in this 2d array?
arr_2d.shape

In [ ]:
# Grab a single row from arr_2d:
arr_2d[0]

In [ ]:
# How to index to the (1,1)th element of the 2 d array
# There are two ways:  arr_2d[1,1] is preferred, but arr_2d[1][1] works as well
arr_2d[1,1]

In [ ]:
# You can also use python-style slices as indices to grab subsections
# of the Matrix
# If we wanted to access the submatrix [10, 15] and [25,30], which is
# rows 0 and 1, columns 1 and 2
# we would say:
arr_2d[:2,1:] 

**Conditional Selection** (this is quite common)

Conditional Selection is how we extract values that meet a particular condition in an array, here's the step-by-step:

In [ ]:
# Set up array with elements 1..10
arr = np.arange(1,11)
arr

In [ ]:
# Create a filter (which ends up being an array of booleans, True where value
# of arr is greater than 4)
bool_arr = arr > 4
print("bool_arr = " + str(bool_arr) + '\n')

# Then you can filter out the array by broadcasting the conditional across
# the elements of the array:
print("Filtered array where arr[i] > 4: " + str(arr[bool_arr])+"\n")

Or the more conventional way to conditionally select in one line:

In [ ]:
# Filter out elements of arr greater than 4 in one line: 
arr[arr>4]

# **Numpy Index Selection**




In [ ]:
#Create some arrays to demonstrate:
arr = np.arange(0,11)
arr

**Extract elements and ranges from an array:**

In [ ]:
# Extract the ith element from the list
arr[8]

In [ ]:
# Extract the ith-through *jth-1* elements from the list
arr[1:5]

In [ ]:
# Extracting from the beginning through ith element:
arr[:5]

In [ ]:
# Extracting from i through end of the array:
arr[5:]

**Broadcasting: means to assign a single value into a range of the original array**

In [ ]:
# Broadcast the value 100 across the first 5 elements of an array
# NOTE THAT THIS IS MUTABLE!!!!
arr[0:5] = 100
arr

In [ ]:
# Reset arr to be [0,10]
arr=np.arange(0,11)


**Note that by default, slices mutate (they are pointers) the array into which they point**

In [ ]:
# Get a MUTABLE ptr into arr
slice_of_arr = arr[0:5]

# Broadcast 99 to the entire slice_of_arr, note that this CHANGES arr
# Note foo[:] implies the entirety of the container
slice_of_arr[:] = 99

# arr will now have the 99 broadcast into it:
arr

**To NOT mutate the array into which a slice ptr points, you need to explicitly make a copy like this (Note that assignment or slicing by default gives you a mutable pointer into the original array):**

In [ ]:
# Reset arr to be [0,10]
arr=np.arange(0,11)

In [ ]:
# Make a copy of the original arr array
arr_copy = arr.copy()

# Slice into the copy:
arr_copy_slice = arr_copy[0:5]

# Mutate the copy:
arr_copy_slice[:] = 99
arr_copy


In [ ]:
# But the original array remains intact:
arr

**Indexing into a 2d array/matrix**

In [ ]:
# Create a 2d array by casting a python list of lists into a numpy array:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [ ]:
# How many Rows and Columns in this 2d array?
arr_2d.shape

In [ ]:
# Grab a single row from arr_2d:
arr_2d[0]

In [ ]:
# How to index to the (1,1)th element of the 2 d array
# There are two ways:  arr_2d[1,1] is preferred, but arr_2d[1][1] works as well
arr_2d[1,1]

In [ ]:
# You can also use python-style slices as indices to grab subsections
# of the Matrix
# If we wanted to access the submatrix [10, 15] and [25,30], which is
# rows 0 and 1, columns 1 and 2
# we would say:
arr_2d[:2,1:] 

**Conditional Selection** (this is quite common)

Conditional Selection is how we extract values that meet a particular condition in an array, here's the step-by-step:

In [ ]:
# Set up array with elements 1..10
arr = np.arange(1,11)
arr

In [ ]:
# Create a filter (which ends up being an array of booleans, True where value
# of arr is greater than 4)
bool_arr = arr > 4
print("bool_arr = " + str(bool_arr) + '\n')

# Then you can filter out the array by broadcasting the conditional across
# the elements of the array:
print("Filtered array where arr[i] > 4: " + str(arr[bool_arr])+"\n")

Or the more conventional way to conditionally select in one line:

In [ ]:
# Filter out elements of arr greater than 4 in one line: 
arr[arr>4]

# **Numpy Operations**




In [ ]:
import numpy as np

# Initialize:
arr = np.arange(0, 10)
print(arr)

**Some Elementary Operations You can do on an array:**
1.  Add/subtract, etc.. a Scalar to an array
2.  Add an array to an array (NOTE:  they need to be the same shape)
3.  Reciprocate every element in an array


In [ ]:
# Add a scalar to an array, adds that scalar to every element of the array:
print("arr: " + str(arr) + "\n")
print("arr + 5: " + str(arr+5) + "\n")
print("arr + arr: " + str(arr+arr) + "\n")

# It's also legal to have the scalar first (note that I selected out
# any zeros to avoid the warning til the next bit of code):
print ("1 / arr: " + str(1/arr[arr>0]) + "\n")

# Interesting note - you get nan when you div by 0, and only a warning
# It doesn't altogether puke
print("arr / arr: " + str(arr/arr) + "\n")

**You can apply more advanced functions on an array**
1.  Square root of every element in an array
2.  Sin of every element in an array
3.  Base 10 log of every element in an array (mind you'll get a warning for log of 0)

In [ ]:
# Apply square root to every element in an array:
print("arr: " + str(arr) + "\n")
print("np.sqrt(arr): " + str(np.sqrt(arr)) + '\n')
print("np.sin(arr): " + str(np.sin(arr)) + '\n')
print("np.log(arr): " + str(np.log(arr)) + '\n')


**Summary statistics on an array**
1.  Mean
2.  Sum
3.  Min/max

In [ ]:
# Sum, mean, max, min:
print("arr: " + str(arr) + "\n")
print("arr.sum(): " + str(arr.sum()) + '\n')
print("arr.mean(): " + str(arr.mean()) + '\n')
print("arr.max()): " + str(arr.max()) + '\n')

# Variance, stddev:
print("arr.var(): " + str(arr.var()) + '\n')
print("arr.std(): " + str(arr.std()) + '\n')

**Summary stats on multi-dimensional structures**

In [ ]:
# Initialize the structure you'll play with:
# A 2 d array with integers from 0-24 as values
array2d = np.arange(0,25).reshape((5,5))

**Perform an operation *across* the rows**
Note that this may defy your intuition - the important word here
is *across*:

so a 3x3 matrix that looks like this:
1 2 3
4 5 6
7 8 9

Then summing across axis=0 (the rows), *goes down, not across*, thus giving you:  [12 15 18]

In [51]:
print("array2d: \n" + str(array2d) + "\n")

# So if you want to sum across the rows (downward), supply the axis 0
# in the argument to the sum:
print ("array2d.sum(0): \n" + str(array2d.sum(0)) + "\n")

# So if you want to sum across the columns (leftright), supply the axis 1
# in the argument to the sum:
print ("array2d.sum(1): \n" + str(array2d.sum(1)) + "\n")

array2d: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

array2d.sum(0): 
[50 55 60 65 70]

array2d.sum(1): 
[ 10  35  60  85 110]

